## Обработка наборов данных с информацией о проектах

In [1]:
import pandas as pd
projects_fall_df = pd.read_csv(r'data/Список проектов - 2023.csv')
projects_spring_df = pd.read_csv(r'data/Список проектов ТП - весна 2024.csv')

In [6]:
projects_spring_df.tail()

,Название,Описание,Требования проекта,Требования к исполнителям,Заказчик,Куратор проекта,Контактная информация Заказчика
0,Модуль отладки динамического поведения графиче...,Имеется набор графических 3х-мерных объектов с...,Клиент отображения (сцена виртуальной реальнос...,Требования:\n - навыки программирования на С++...,Росатом,"Блеканов И.С., Орехов М.Ю.","Михаил Юрьевич Орехов, \nТелеграм (доступен по..."
1,Автоматическая цветовая коррекция,Автоматическая цветовая коррекция необходима д...,1.\tВ реализации алгоритма не должны применятс...,"1.\tПонимание технологий WebGL, JavaScript, Ca...",СТЦ,И.С. Блеканов,"Алексей,\nТелеграм: @komalmex"
2,Алгоритм Retinex,Целью данного проекта является разработка и ре...,1.\tВ реализации алгоритма не должны применятс...,"1.\tПонимание принципов работы с WebGL, JavaSc...",СТЦ,И.С. Блеканов,"Алексей,\nТелеграм: @komalmex"
3,Интеллектуальное возвращение БпЛА в точку стар...,"Проект посвящён управлению БпЛА, оснащённого к...",1. Система должна автоматически начинать свою ...,Язык программирования: С++\nПрограммирование e...,Гескан,И.С. Блеканов,Матросов Валерий Витальевич. Руководитель отде...
4,Автоматизация сбора и обработки пространственн...,В мире существует не только большое количество...,"Ожидаемый результат:\nАртефакты, использование...",Умение или готовность к быстрому освоению рабо...,Центра аналитики динамических процессов и сист...,С.Ю. Севрюков,Профессор А.Ю. Крылатов

In [ ]:
projects_fall_df.iloc[]

In [3]:
from data_preparation import preprocess_project_data

In [4]:
auth_token = '*Здесь должен быть ваш токен*'

In [4]:
new_projects_fall_df = preprocess_project_data(auth_token, projects_fall_df)
new_projects_spring_df = preprocess_project_data(auth_token, projects_spring_df)

In [6]:
new_projects_fall_df.head()

,Название,Описание,Требования проекта,Требования к исполнителям,Заказчик,Куратор проекта,Контактная информация Заказчика,Тема проекта,Роли исполнителей,hard skills,Важность ролей
0,Модуль планирования расходных материалов,"Каждая медицинская услуга, оказываемая учрежде...","Разработать концепцию работы модуля, интерфейс...",Знание базовых основ построения веб-сервисов и...,"Компания ""Виста""",Блеканов И.С.,"Лазебникова Полина, 89148700715, qqpln@mail.ru\n",Анализ табличных данных,1. Data Science\n2. Backend - разработка\n3. F...,"Python, JavaScript, HTML/CSS, SQL, React, Node.js",1. Data Science - 3\n2. Дизайн UX / UI и проек...
1,Личный кабинет пациента,Пациенты довольно часто обращаются в медицинск...,Разработать концепцию работы личного кабинета ...,Знание базовых основ построения веб-сервисов и...,"Компания ""Виста""",Блеканов И.С.,"Лазебникова Полина, 89148700715, qqpln@mail.ru",Разработка веб-сервисов,1. Data Science\n2. Backend - разработка\n3. F...,"Python, Django, HTML, CSS, JavaScript, jQuery,...",1. Data Science - 2\n2. Дизайн UX / UI и проек...
2,Смарт-клиника,Работа главного врача связана с частым сбором ...,1. Разработать концепцию работы “Рабочего стол...,"""Знание базовых основ построения веб-сервисов ...","Компания ""Виста""",Блеканов И.С.,"Лазебникова Полина, 89148700715, qqpln@mail.ru\n",Разработка веб-сервисов,1. Data Science\n2. Backend - разработка\n3. F...,"php, mysql, html, css, js, jquery, ajax",1. Data Science - 3\n2. Дизайн UX / UI и проек...
3,Детектирование аорты сердца на снимках КТ,Существуют сложные случаи сердечно-сосудистых ...,1. Разработать модель глубокого обучения для с...,● Знание базовых основ построения веб-сервисов...,Клиника высоких медицинских технологий им. Н.И...,"И.С. Блеканов, Коваленко Лев","И.С. Блеканов, Лев Коваленко, Ким Глеб",Разработка веб-сервисов,1. Data Science\n2. Backend - разработка\n3. F...,"Python, TensorFlow/PyTorch, scikit-learn, HTML...",1. Data Science - 4\n2. Дизайн UX / UI и проек...
4,Геоинформационная система для точного земледелия,Для реализации цифрового двойника в умном раст...,"""1. Разработать концепцию единого Веб-сервиса,...",●Знание базовых основ построения веб-сервисов ...,Агрофизический институт,"И.С. Блеканов, Лев Коваленко","Митрофанов Евгений Павлович, +79817597773, mje...",Разработка веб-сервисов,1. Data Science\n2. Backend - разработка\n3. F...,"Python, JavaScript, HTML/CSS, PostgreSQL, PostGIS",1. Data Science - 3\n2. Дизайн UX / UI и проек...

In [7]:
new_projects_fall_df.to_csv('data\prepared_fall_2023.csv')

In [8]:
new_projects_spring_df.to_csv('data\prepared_spring_2023.csv')

In [2]:
import pandas as pd
new_projects_fall_df = pd.read_csv('data\prepared_fall_2023.csv')
new_projects_spring_df = pd.read_csv('data\prepared_spring_2023.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'data\\prepared_spring_2023.csv'

Пример работы вспомогательных функций

In [2]:
from data_preparation import preprocess_roles, preprocess_hard_skills, preprocess_scoring

In [3]:
print(new_projects_fall_df['Роли исполнителей'][0])

1. Data Science
2. Backend - разработка
3. Frontend - разработка
4. Тестировщик
5. DevOps

In [4]:
preprocess_roles(new_projects_fall_df['Роли исполнителей'][0])

['Data Science',
 'Backend - разработка',
 'Frontend - разработка',
 'Тестировщик',
 'DevOps']

In [5]:
print(new_projects_fall_df['hard skills'][0])

Python, JavaScript, HTML/CSS, SQL, React, Node.js

In [6]:
preprocess_hard_skills(new_projects_fall_df['hard skills'][0])

['Python', 'JavaScript', 'HTML', 'CSS', 'SQL', 'React', 'Node.js']

In [7]:
print(new_projects_fall_df['Важность ролей'][0])

1. Data Science - 3
2. Дизайн UX / UI и проектирование интерфейсов - 4
3. Backend - разработка - 4
4. Frontend - разработка - 4
5. Тестировщик - 2
6. devOps - 2

In [10]:
preprocess_scoring(new_projects_fall_df['Важность ролей'][0])

{'Data Science': 3,
 'Дизайн UX / UI и проектирование интерфейсов': 4,
 'Backend - разработка': 4,
 'Frontend - разработка': 4,
 'Тестировщик': 2,
 'devOps': 2}

Пример использования функции для обработки оценки компетенций участниками в словари

In [11]:
import pandas as pd
data_df = pd.read_excel('data\Анкета - весна 24 (Ответы).xlsx')
preprocess_scoring(data_df['Инструменты для разработки ПО - например: VS Code, PyCharm, Git, etc)'][0])

{'PyCharm': 2, 'Git': 1}